---
version: "2.1"

services:
  k3s:
    build: ./k3s
    container_name: k3s
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    network_mode: host
    restart: always
    volumes:
      - rancher_etc:/etc/rancher
    #volumes:
    #  - k3s_lib:/var/lib/rancher/k3s
    environment:
      - K3S_URL=${K3S_URL}
      - K3S_TOKEN=${K3S_TOKEN:?err}
    labels:
      io.balena.features.balena-socket: '1'
      io.balena.features.sysfs: '1'

  #wireguard:
  #  image: lscr.io/linuxserver/wireguard:latest
  #  container_name: wireguard
  #  cap_add:
  #    - NET_ADMIN
  #    - SYS_MODULE
  #  network_mode: host
  #  environment:
  #    - PUID=1000
  #    - PGID=1000
  #    - TZ=${TZ:-UTC}
      #- SERVERURL=wireguard.domain.com #optional
      #- SERVERPORT=51820 #optional
      #- PEERS=1 #optional
      #- PEERDNS=auto #optional
      #- INTERNAL_SUBNET=10.13.13.0 #optional
      #- ALLOWEDIPS=0.0.0.0/0 #optional
  #  volumes:
  #    - wireguard_config:/config
  #  labels:
  #    io.balena.features.kernel-modules: '1'
  #  sysctls:
  #    - net.ipv4.conf.all.src_valid_mark=1
  #  restart: unless-stopped  

volumes:
  rancher_etc: {}
  wireguard_config: {}

