---
version: "2.1"

services:
  k3s:
    build: ./k3s
    container_name: k3s
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    network_mode: host
    restart: always
    volumes:
      - rancher_etc:/etc/rancher
      - calico_data_dir:/var/lib/calico
      - k3s_data_dir:/var/lib/rancher/k3s
      - k3s_flexvol:/opt/libexec/kubernetes/kubelet-plugins/volume/exec
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
      - K3S_URL=${K3S_URL}
      - K3S_TOKEN=${K3S_TOKEN:?err}
    labels:
      io.balena.features.balena-socket: '1'
      io.balena.features.dbus: '1'

  wireguard:
    build: ./wireguard
    privileged: true
    network_mode: host
    labels:
      io.balena.features.kernel-modules: '1'

volumes:
  calico_data_dir: {}
  k3s_data_dir: {}
  k3s_flexvol: {}
  rancher_etc: {}
  wireguard_config: {}

